import Link from 'next/link';
import { requireAdmin } from '@/lib/auth/dal';
import { db } from '@/lib/neon/db';

export const dynamic = 'force-dynamic';

export default async function AdminDashboardPage() {
  const admin = await requireAdmin();
  let proposalCount = 0; let pendingReports = 0; let unreadMessages = 0;
  if (db) { const [proposals, reports, notifications] = await Promise.all([db.$client.query('select count(*)::integer as count from proposals'), db.$client.query('select count(*)::integer as count from reports where resolved_at is null'), db.$client.query('select count(*)::integer as count from notifications where recipient_id = $1 and read_at is null', [admin.userId])]); proposalCount = Number(proposals.rows[0]?.count ?? 0); pendingReports = Number(reports.rows[0]?.count ?? 0); unreadMessages = Number(notifications.rows[0]?.count ?? 0); }
  return <main className="min-h-screen bg-[#080808] px-4 py-8 text-[#f0ede8] sm:px-6 sm:py-12 md:px-10"><div className="mx-auto max-w-6xl"><Link href="/" className="inline-flex min-h-11 items-center font-mono text-xs tracking-[0.16em] text-[#c8a45a] hover:text-white">← AIueoへ戻る</Link><header className="mt-8 sm:mt-12"><p className="font-mono text-xs tracking-[0.2em] text-[#c8a45a]">ADMIN CONSOLE</p><h1 className="mt-4 text-4xl font-light sm:text-5xl">管理画面</h1><p className="mt-4 leading-8 text-white/70">通常の企画審査は行いません。全企画の編集・状態変更・非公開、会員措置、通報対応を行います。</p></header><div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="border border-white/15 bg-[#12110d] p-5"><p className="form-label">全企画</p><p className="mt-2 text-3xl font-light">{proposalCount}</p></div><div className="border border-white/15 bg-[#12110d] p-5"><p className="form-label">未処理通報</p><p className="mt-2 text-3xl font-light">{pendingReports}</p></div><div className="border border-white/15 bg-[#12110d] p-5"><p className="form-label">未読通知</p><p className="mt-2 text-3xl font-light">{unreadMessages}</p></div></div><nav className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Link href="/admin/proposals" className="border border-[#c8a45a]/50 bg-[#12110d] p-5 transition-colors hover:border-[#c8a45a]"><span className="form-label">01</span><h2 className="mt-2 text-xl">企画管理</h2><p className="mt-2 text-xs text-white/55">企画詳細からメッセージも開けます</p></Link><Link href="/admin/members" className="border border-[#c8a45a]/50 bg-[#12110d] p-5 transition-colors hover:border-[#c8a45a]"><span className="form-label">02</span><h2 className="mt-2 text-xl">会員管理</h2></Link><Link href="/admin/moderation" className="border border-[#c8a45a]/50 bg-[#12110d] p-5 transition-colors hover:border-[#c8a45a]"><span className="form-label">03</span><h2 className="mt-2 text-xl">通報・措置</h2></Link></nav></div></main>;
}
